# Generated by Django 3.1.3 on 2020-11-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail_party_maker', '0002_cocktail_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='state',
            field=models.CharField(choices=[('PD', 'Pending'), ('AC', 'Accepted'), ('RF', 'Refused')], default='PD', max_length=2),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='color',
            field=models.CharField(choices=[('Red', 'red'), ('Orange', 'orange'), ('Yellow', 'yellow'), ('Olive', 'olive'), ('Green', 'green'), ('Teal', 'teal'), ('Blue', 'blue'), ('Violet', 'violet'), ('Purple', 'purple'), ('Pink', 'pink'), ('Brown', 'brown'), ('Grey', 'grey'), ('Black', 'black')], default='grey', max_length=7),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
