# Generated by Django 3.1.3 on 2020-11-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="creation_date",
        ),
    ]
